"""ASR v0.1 pipeline building blocks."""

from core.pipelines.asr.diarize import (
    AudioDiarizeError,
    DiarizationResult,
    DiarizationSegment,
    PyannotePipelineConfig,
    configure_ffmpeg_shared_dll_directory,
    diarize_audio,
    load_pyannote_pipeline,
    segments_from_pyannote_output,
)
from core.pipelines.asr.normalize import AudioNormalizeError, AudioStreamInfo, NormalizeResult, normalize_audio, probe_audio_stream
from core.pipelines.asr.quality import (
    QualityConfig,
    ResultSafetyDecision,
    SegmentQualityDecision,
    detect_repetition_collapse,
    detect_word_density_anomaly,
    evaluate_result_safety,
    evaluate_segment,
    is_stock_artifact,
)
from core.pipelines.asr.transcribe import (
    AudioTranscribeError,
    TranscriptSegment,
    TranscribeChunk,
    TranscribeResult,
    WhisperModelConfig,
    build_transcribe_chunks,
    load_whisper_model,
    transcribe_vad_segments,
)
from core.pipelines.asr.vad import AudioVadError, VadResult, VadSpeechSegment, run_silero_vad

__all__ = [
    "AudioNormalizeError",
    "AudioTranscribeError",
    "AudioDiarizeError",
    "AudioVadError",
    "AudioStreamInfo",
    "DiarizationResult",
    "DiarizationSegment",
    "NormalizeResult",
    "PyannotePipelineConfig",
    "QualityConfig",
    "ResultSafetyDecision",
    "SegmentQualityDecision",
    "TranscriptSegment",
    "TranscribeChunk",
    "TranscribeResult",
    "WhisperModelConfig",
    "VadResult",
    "VadSpeechSegment",
    "build_transcribe_chunks",
    "configure_ffmpeg_shared_dll_directory",
    "detect_repetition_collapse",
    "detect_word_density_anomaly",
    "diarize_audio",
    "evaluate_result_safety",
    "evaluate_segment",
    "is_stock_artifact",
    "load_whisper_model",
    "load_pyannote_pipeline",
    "normalize_audio",
    "probe_audio_stream",
    "run_silero_vad",
    "segments_from_pyannote_output",
    "transcribe_vad_segments",
]
